# Generated by Django 5.1.6 on 2025-03-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='favourite_vacancies',
            field=models.ManyToManyField(blank=True, to='jobs.vacancy'),
        ),
    ]
