# Generated by Django 5.1.6 on 2025-03-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobseekerprofile_favourite_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='jobs.vacancy'),
        ),
    ]
